version: '3'
services:
  app:
    image: realdreamcoding/docker-example:latest
    ports:
      - 8080:8080
    depends_on:
      - mysql

  mysql:
    image: mysql/mysql-server:8.0.25
    command: --default-authentication-plugin=mysql_native_password

    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secretRootPassword
    